services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    image: vasanthreddyo07/newmongo-login:latest
    container_name: hrms
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/loginDB
    depends_on:
      - mongo

volumes:
  mongo_data:
